//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: AddCommand.proto

// Note: requires additional types generated from: QueryInfo.proto
// Note: requires additional types generated from: TagInfo.proto
// Note: requires additional types generated from: NamedTagInfo.proto
// Note: requires additional types generated from: ObjectQueryInfo.proto
namespace Alachisoft.NCache.Common.Protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddCommand")]
  public partial class AddCommand : global::ProtoBuf.IExtensible
  {
    public AddCommand() {}
    

    private string _key = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string key
    {
      get { return _key; }
      set { _key = value; }
    }

    private long _requestId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"requestId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long requestId
    {
      get { return _requestId; }
      set { _requestId = value; }
    }

    private int _updateCallbackId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"updateCallbackId", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int updateCallbackId
    {
      get { return _updateCallbackId; }
      set { _updateCallbackId = value; }
    }

    private int _removeCallbackId = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"removeCallbackId", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int removeCallbackId
    {
      get { return _removeCallbackId; }
      set { _removeCallbackId = value; }
    }

    private int _datasourceItemAddedCallbackId = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"datasourceItemAddedCallbackId", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int datasourceItemAddedCallbackId
    {
      get { return _datasourceItemAddedCallbackId; }
      set { _datasourceItemAddedCallbackId = value; }
    }

    private bool _isAsync = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"isAsync", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isAsync
    {
      get { return _isAsync; }
      set { _isAsync = value; }
    }

    private int _priority = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"priority", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int priority
    {
      get { return _priority; }
      set { _priority = value; }
    }

    private long _absExpiration = default(long);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"absExpiration", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long absExpiration
    {
      get { return _absExpiration; }
      set { _absExpiration = value; }
    }

    private long _sldExpiration = default(long);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"sldExpiration", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long sldExpiration
    {
      get { return _sldExpiration; }
      set { _sldExpiration = value; }
    }

    private bool _isResync = default(bool);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"isResync", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isResync
    {
      get { return _isResync; }
      set { _isResync = value; }
    }


    private string _subGroup = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"subGroup", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string subGroup
    {
      get { return _subGroup; }
      set { _subGroup = value; }
    }

    private int _flag = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int flag
    {
      get { return _flag; }
      set { _flag = value; }
    }

    private string _providerName = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"providerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string providerName
    {
      get { return _providerName; }
      set { _providerName = value; }
    }

    private string _resyncProviderName = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"resyncProviderName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string resyncProviderName
    {
      get { return _resyncProviderName; }
      set { _resyncProviderName = value; }
    }
        
    private readonly global::System.Collections.Generic.List<byte[]> _data = new global::System.Collections.Generic.List<byte[]>();
    [global::ProtoBuf.ProtoMember(20, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<byte[]> data
    {
      get { return _data; }
    }
   
    private readonly global::System.Collections.Generic.List<byte[]> _objectQueryInfoEncrypted = new global::System.Collections.Generic.List<byte[]>();
    [global::ProtoBuf.ProtoMember(23, Name=@"objectQueryInfoEncrypted", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<byte[]> objectQueryInfoEncrypted
    {
      get { return _objectQueryInfoEncrypted; }
    }
  

    private int _updateDataFilter = (int)-1;
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"updateDataFilter", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int updateDataFilter
    {
      get { return _updateDataFilter; }
      set { _updateDataFilter = value; }
    }

    private int _removeDataFilter = (int)-1;
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"removeDataFilter", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int removeDataFilter
    {
      get { return _removeDataFilter; }
      set { _removeDataFilter = value; }
    }

    private string _clientID = "";
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"clientID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string clientID
    {
      get { return _clientID; }
      set { _clientID = value; }
    }

    private int _CallbackType = default(int);
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"CallbackType", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int CallbackType
    {
      get { return _CallbackType; }
      set { _CallbackType = value; }
    }


    private string _version = "";
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string version
    {
      get { return _version; }
      set { _version = value; }
    }

    private int _MethodOverload = (int)0;
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"MethodOverload", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int MethodOverload
    {
      get { return _MethodOverload; }
      set { _MethodOverload = value; }
    }

    private int _commandID = (int)-1;
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"commandID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int commandID
    {
      get { return _commandID; }
      set { _commandID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}