//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ClearCommand.proto
namespace Alachisoft.NCache.Common.Protobuf
{
  [global::System.Serializable, global::ProtoBuf.Extended.ProtoContract(Name=@"ClearCommand")]
  public partial class ClearCommand : global::ProtoBuf.Extended.IExtensible
  {
    public ClearCommand() {}
    

    private long _requestId = default(long);
        [global::ProtoBuf.Extended.ProtoMember(1, IsRequired = false, Name = @"requestId", DataFormat = global::ProtoBuf.Extended.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(long))]
        public long requestId
    {
      get { return _requestId; }
      set { _requestId = value; }
    }

    private bool _isAsync = default(bool);
    [global::ProtoBuf.Extended.ProtoMember(2, IsRequired = false, Name=@"isAsync", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isAsync
    {
      get { return _isAsync; }
      set { _isAsync = value; }
    }

    private int _flag = default(int);
    [global::ProtoBuf.Extended.ProtoMember(3, IsRequired = false, Name=@"flag", DataFormat = global::ProtoBuf.Extended.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int flag
    {
      get { return _flag; }
      set { _flag = value; }
    }

    private int _datasourceClearedCallbackId = default(int);
    [global::ProtoBuf.Extended.ProtoMember(4, IsRequired = false, Name=@"datasourceClearedCallbackId", DataFormat = global::ProtoBuf.Extended.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int datasourceClearedCallbackId
    {
      get { return _datasourceClearedCallbackId; }
      set { _datasourceClearedCallbackId = value; }
    }

    private string _providerName = "";
    [global::ProtoBuf.Extended.ProtoMember(5, IsRequired = false, Name=@"providerName", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string providerName
    {
      get { return _providerName; }
      set { _providerName = value; }
    }

    private int _MethodOverload = (int)0;
    [global::ProtoBuf.Extended.ProtoMember(6, IsRequired = false, Name=@"MethodOverload", DataFormat = global::ProtoBuf.Extended.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int MethodOverload
    {
      get { return _MethodOverload; }
      set { _MethodOverload = value; }
    }

    private int _commandID = (int)-1;
    [global::ProtoBuf.Extended.ProtoMember(7, IsRequired = false, Name=@"commandID", DataFormat = global::ProtoBuf.Extended.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int commandID
    {
      get { return _commandID; }
      set { _commandID = value; }
    }
    private global::ProtoBuf.Extended.IExtension extensionObject;
   global::ProtoBuf.Extended.IExtension global::ProtoBuf.Extended.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extended.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}