//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: DependencyItem.proto
// Note: requires additional types generated from: Dependency.proto
namespace Alachisoft.NCache.Common.Protobuf
{
  [global::System.Serializable, global::ProtoBuf.Extended.ProtoContract(Name=@"DependencyItem")]
  public partial class DependencyItem : global::ProtoBuf.Extended.IExtensible
  {
    public DependencyItem() {}
    
    private string _key;
    [global::ProtoBuf.Extended.ProtoMember(1, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    public string key
    {
      get { return _key; }
      set { _key = value; }
    }
   
    private global::ProtoBuf.Extended.IExtension extensionObject;
   global::ProtoBuf.Extended.IExtension global::ProtoBuf.Extended.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extended.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
