//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: EnumerationPointer.proto
namespace Alachisoft.NCache.Common.Protobuf
{
  [global::System.Serializable, global::ProtoBuf.Extended.ProtoContract(Name=@"EnumerationPointer")]
  public partial class EnumerationPointer : global::ProtoBuf.Extended.IExtensible
  {
    public EnumerationPointer() {}
    

    private int _chunkId = default(int);
    [global::ProtoBuf.Extended.ProtoMember(1, IsRequired = false, Name=@"chunkId", DataFormat = global::ProtoBuf.Extended.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int chunkId
    {
      get { return _chunkId; }
      set { _chunkId = value; }
    }

    private string _id = "";
    [global::ProtoBuf.Extended.ProtoMember(2, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }

    private bool _isDisposed = default(bool);
    [global::ProtoBuf.Extended.ProtoMember(3, IsRequired = false, Name=@"isDisposed", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isDisposed
    {
      get { return _isDisposed; }
      set { _isDisposed = value; }
    }
    private global::ProtoBuf.Extended.IExtension extensionObject;
   global::ProtoBuf.Extended.IExtension global::ProtoBuf.Extended.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extended.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
