// Copyright (c) 2018 Alachisoft
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//    http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ObjectQueryInfo.proto
// Note: requires additional types generated from: QueryInfo.proto
// Note: requires additional types generated from: TagInfo.proto
// Note: requires additional types generated from: NamedTagInfo.proto
namespace Alachisoft.NCache.Common.Protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ObjectQueryInfo")]
  public partial class ObjectQueryInfo : global::ProtoBuf.IExtensible
  {
    public ObjectQueryInfo() {}
    

    private Alachisoft.NCache.Common.Protobuf.NamedTagInfo _namedTagInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"namedTagInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.NamedTagInfo namedTagInfo
    {
      get { return _namedTagInfo; }
      set { _namedTagInfo = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.TagInfo _tagInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tagInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.TagInfo tagInfo
    {
      get { return _tagInfo; }
      set { _tagInfo = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.QueryInfo _queryInfo = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"queryInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.QueryInfo queryInfo
    {
      get { return _queryInfo; }
      set { _queryInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
