//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RaiseCustomEventCommand.proto
namespace Alachisoft.NCache.Common.Protobuf
{
  [global::System.Serializable, global::ProtoBuf.Extended.ProtoContract(Name=@"RaiseCustomEventCommand")]
  public partial class RaiseCustomEventCommand : global::ProtoBuf.Extended.IExtensible
  {
    public RaiseCustomEventCommand() {}
    

    private long _requestId = default(long);
    [global::ProtoBuf.Extended.ProtoMember(1, IsRequired = false, Name=@"requestId", DataFormat = global::ProtoBuf.Extended.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long requestId
    {
      get { return _requestId; }
      set { _requestId = value; }
    }

    private byte[] _notifIf = null;
    [global::ProtoBuf.Extended.ProtoMember(2, IsRequired = false, Name=@"notifIf", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] notifIf
    {
      get { return _notifIf; }
      set { _notifIf = value; }
    }

    private byte[] _data = null;
    [global::ProtoBuf.Extended.ProtoMember(3, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }

    private int _MethodOverload = (int)0;
    [global::ProtoBuf.Extended.ProtoMember(4, IsRequired = false, Name=@"MethodOverload", DataFormat = global::ProtoBuf.Extended.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int MethodOverload
    {
      get { return _MethodOverload; }
      set { _MethodOverload = value; }
    }
    private global::ProtoBuf.Extended.IExtension extensionObject;
   global::ProtoBuf.Extended.IExtension global::ProtoBuf.Extended.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extended.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}