//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RegisterPollingNotificationCommand.proto
namespace Alachisoft.NCache.Common.Protobuf
{
  [global::System.Serializable, global::ProtoBuf.Extended.ProtoContract(Name=@"RegisterPollingNotificationCommand")]
  public partial class RegisterPollingNotificationCommand : global::ProtoBuf.Extended.IExtensible
  {
    public RegisterPollingNotificationCommand() {}
    

    private long _requestId = default(long);
    [global::ProtoBuf.Extended.ProtoMember(1, IsRequired = false, Name=@"requestId", DataFormat = global::ProtoBuf.Extended.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long requestId
    {
      get { return _requestId; }
      set { _requestId = value; }
    }

    private int _callbackId = default(int);
    [global::ProtoBuf.Extended.ProtoMember(2, IsRequired = false, Name=@"callbackId", DataFormat = global::ProtoBuf.Extended.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int callbackId
    {
      get { return _callbackId; }
      set { _callbackId = value; }
    }

    private long _clientLastViewId = (long)-1;
    [global::ProtoBuf.Extended.ProtoMember(3, IsRequired = false, Name=@"clientLastViewId", DataFormat = global::ProtoBuf.Extended.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)-1)]
    public long clientLastViewId
    {
      get { return _clientLastViewId; }
      set { _clientLastViewId = value; }
    }
    private global::ProtoBuf.Extended.IExtension extensionObject;
   global::ProtoBuf.Extended.IExtension global::ProtoBuf.Extended.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extended.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}