//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: NCManagementResponse.proto
// Note: requires additional types generated from: StartCacheResponse.proto
// Note: requires additional types generated from: Exception.proto
namespace Alachisoft.NCache.Common.Protobuf
{
  [global::System.Serializable, global::ProtoBuf.Extended.ProtoContract(Name=@"NCManagementResponse")]
  public partial class NCManagementResponse : global::ProtoBuf.Extended.IExtensible
  {
    public NCManagementResponse() {}
    

    private long _requestId = default(long);
    [global::ProtoBuf.Extended.ProtoMember(1, IsRequired = false, Name=@"requestId", DataFormat = global::ProtoBuf.Extended.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long requestId
    {
      get { return _requestId; }
      set { _requestId = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.NCManagementResponse.Type _responseType = Alachisoft.NCache.Common.Protobuf.NCManagementResponse.Type.START_CACHE;
    [global::ProtoBuf.Extended.ProtoMember(2, IsRequired = false, Name=@"responseType", DataFormat = global::ProtoBuf.Extended.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Alachisoft.NCache.Common.Protobuf.NCManagementResponse.Type.START_CACHE)]
    public Alachisoft.NCache.Common.Protobuf.NCManagementResponse.Type responseType
    {
      get { return _responseType; }
      set { _responseType = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.Exception _exception = null;
    [global::ProtoBuf.Extended.ProtoMember(3, IsRequired = false, Name=@"exception", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.Exception exception
    {
      get { return _exception; }
      set { _exception = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.StartCacheResponse _startCache = null;
    [global::ProtoBuf.Extended.ProtoMember(4, IsRequired = false, Name=@"startCache", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.StartCacheResponse startCache
    {
      get { return _startCache; }
      set { _startCache = value; }
    }
    [global::ProtoBuf.Extended.ProtoContract(Name=@"Type")]
    public enum Type
    {
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"START_CACHE", Value=1)]
      START_CACHE = 1
    }
  
    private global::ProtoBuf.Extended.IExtension extensionObject;
   global::ProtoBuf.Extended.IExtension global::ProtoBuf.Extended.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extended.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
