//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: CacheItemType.proto
namespace Alachisoft.NCache.Common.Protobuf
{
  [global::System.Serializable, global::ProtoBuf.Extended.ProtoContract(Name=@"CacheItemType")]
  public partial class CacheItemType : global::ProtoBuf.Extended.IExtensible
  {
    public CacheItemType() {}
    
    [global::ProtoBuf.Extended.ProtoContract(Name=@"ItemType")]
    public enum ItemType
    {
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"CACHEITEM", Value=1)]
      CACHEITEM = 1,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"LIST", Value=2)]
      LIST = 2,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"QUEUE", Value=3)]
      QUEUE = 3,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"SET", Value=4)]
      SET = 4,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"DICTIONARY", Value=5)]
      DICTIONARY = 5,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"COUNTER", Value=6)]
      COUNTER = 6
    }
  
    private global::ProtoBuf.Extended.IExtension extensionObject;
   global::ProtoBuf.Extended.IExtension global::ProtoBuf.Extended.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extended.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}