// Copyright (c) 2015 Alachisoft
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//    http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Exception.proto
namespace Alachisoft.NCache.Common.Protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Exception")]
  public partial class Exception : global::ProtoBuf.IExtensible
  {
    public Exception() {}
    

    private Alachisoft.NCache.Common.Protobuf.Exception.Type _type = Alachisoft.NCache.Common.Protobuf.Exception.Type.OPERATIONFAILED;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Alachisoft.NCache.Common.Protobuf.Exception.Type.OPERATIONFAILED)]
    public Alachisoft.NCache.Common.Protobuf.Exception.Type type
    {
      get { return _type; }
      set { _type = value; }
    }

    private string _message = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }

    private string _exception = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"exception", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string exception
    {
      get { return _exception; }
      set { _exception = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Type")]
    public enum Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPERATIONFAILED", Value=0)]
      OPERATIONFAILED = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AGGREGATE", Value=1)]
      AGGREGATE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONFIGURATION", Value=2)]
      CONFIGURATION = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GENERALFAILURE", Value=3)]
      GENERALFAILURE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTSUPPORTED", Value=4)]
      NOTSUPPORTED = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAX_CLIENTS_REACHED", Value=5)]
      MAX_CLIENTS_REACHED = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_INDEX_NOT_FOUND", Value=6)]
      TYPE_INDEX_NOT_FOUND = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTRIBUTE_INDEX_NOT_FOUND", Value=7)]
      ATTRIBUTE_INDEX_NOT_FOUND = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STATE_TRANSFER_EXCEPTION", Value=8)]
      STATE_TRANSFER_EXCEPTION = 8
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
