//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ExecuteReaderResponse.proto
// Note: requires additional types generated from: ReaderResultSet.proto
namespace Alachisoft.NCache.Common.Protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExecuteReaderResponse")]
  public partial class ExecuteReaderResponse : global::ProtoBuf.IExtensible
  {
    public ExecuteReaderResponse() {}
    
    private readonly global::System.Collections.Generic.List<Alachisoft.NCache.Common.Protobuf.ReaderResultSet> _readerResultSets = new global::System.Collections.Generic.List<Alachisoft.NCache.Common.Protobuf.ReaderResultSet>();
    [global::ProtoBuf.ProtoMember(1, Name=@"readerResultSets", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Alachisoft.NCache.Common.Protobuf.ReaderResultSet> readerResultSets
    {
      get { return _readerResultSets; }
    }
  

    private long _requestId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"requestId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long requestId
    {
      get { return _requestId; }
      set { _requestId = value; }
    }

    private int _commandID = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"commandID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int commandID
    {
      get { return _commandID; }
      set { _commandID = value; }
    }

    private int _sequenceId = (int)1;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sequenceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)1)]
    public int sequenceId
    {
      get { return _sequenceId; }
      set { _sequenceId = value; }
    }

    private int _numberOfChuncks = (int)1;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"numberOfChuncks", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)1)]
    public int numberOfChuncks
    {
      get { return _numberOfChuncks; }
      set { _numberOfChuncks = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}