//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: FragmentedResponse.proto
namespace Alachisoft.NCache.Common.Protobuf
{
  [global::System.Serializable, global::ProtoBuf.Extended.ProtoContract(Name=@"FragmentedResponse")]
  public partial class FragmentedResponse : global::ProtoBuf.Extended.IExtensible
  {
    public FragmentedResponse() {}
    

    private long _messageId = default(long);
    [global::ProtoBuf.Extended.ProtoMember(1, IsRequired = false, Name=@"messageId", DataFormat = global::ProtoBuf.Extended.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long messageId
    {
      get { return _messageId; }
      set { _messageId = value; }
    }

    private int _fragmentNo = default(int);
    [global::ProtoBuf.Extended.ProtoMember(2, IsRequired = false, Name=@"fragmentNo", DataFormat = global::ProtoBuf.Extended.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fragmentNo
    {
      get { return _fragmentNo; }
      set { _fragmentNo = value; }
    }

    private int _totalFragments = default(int);
    [global::ProtoBuf.Extended.ProtoMember(3, IsRequired = false, Name=@"totalFragments", DataFormat = global::ProtoBuf.Extended.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int totalFragments
    {
      get { return _totalFragments; }
      set { _totalFragments = value; }
    }

    private byte[] _message = null;
    [global::ProtoBuf.Extended.ProtoMember(4, IsRequired = false, Name=@"message", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.Extended.IExtension extensionObject;
   global::ProtoBuf.Extended.IExtension global::ProtoBuf.Extended.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extended.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
