//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GetGroupNextChunkResponse.proto
// Note: requires additional types generated from: Commands/GroupEnumerationPointer.proto
namespace Alachisoft.NCache.Common.Protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetGroupNextChunkResponse")]
  public partial class GetGroupNextChunkResponse : global::ProtoBuf.IExtensible
  {
    public GetGroupNextChunkResponse() {}
    

    private Alachisoft.NCache.Common.Protobuf.GroupEnumerationPointer _groupEnumerationPointer = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"groupEnumerationPointer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.GroupEnumerationPointer groupEnumerationPointer
    {
      get { return _groupEnumerationPointer; }
      set { _groupEnumerationPointer = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _keys = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"keys", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> keys
    {
      get { return _keys; }
    }
  

    private int _commandID = (int)-1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"commandID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int commandID
    {
      get { return _commandID; }
      set { _commandID = value; }
    }

    private long _requestId = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"requestId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long requestId
    {
      get { return _requestId; }
      set { _requestId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}