//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: KeyCacheItemPair.proto
// Note: requires additional types generated from: GetCacheItemResponse.proto
namespace Alachisoft.NCache.Common.Protobuf
{
  [global::System.Serializable, global::ProtoBuf.Extended.ProtoContract(Name=@"KeyCacheItemPair")]
  public partial class KeyCacheItemPair : global::ProtoBuf.Extended.IExtensible
  {
    public KeyCacheItemPair() {}
    

    private string _key = "";
    [global::ProtoBuf.Extended.ProtoMember(1, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string key
    {
      get { return _key; }
      set { _key = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.GetCacheItemResponse _cacheItem = null;
    [global::ProtoBuf.Extended.ProtoMember(2, IsRequired = false, Name=@"cacheItem", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.GetCacheItemResponse cacheItem
    {
      get { return _cacheItem; }
      set { _cacheItem = value; }
    }
    private global::ProtoBuf.Extended.IExtension extensionObject;
   global::ProtoBuf.Extended.IExtension global::ProtoBuf.Extended.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extended.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}