//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LockResponse.proto
namespace Alachisoft.NCache.Common.Protobuf
{
  [global::System.Serializable, global::ProtoBuf.Extended.ProtoContract(Name=@"LockResponse")]
  public partial class LockResponse : global::ProtoBuf.Extended.IExtensible
  {
    public LockResponse() {}
    

    private bool _locked = default(bool);
    [global::ProtoBuf.Extended.ProtoMember(1, IsRequired = false, Name=@"locked", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool locked
    {
      get { return _locked; }
      set { _locked = value; }
    }

    private string _lockId = "";
    [global::ProtoBuf.Extended.ProtoMember(2, IsRequired = false, Name=@"lockId", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string lockId
    {
      get { return _lockId; }
      set { _lockId = value; }
    }

    private long _lockTime = default(long);
    [global::ProtoBuf.Extended.ProtoMember(3, IsRequired = false, Name=@"lockTime", DataFormat = global::ProtoBuf.Extended.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long lockTime
    {
      get { return _lockTime; }
      set { _lockTime = value; }
    }

    private int _commandID = (int)-1;
    [global::ProtoBuf.Extended.ProtoMember(4, IsRequired = false, Name=@"commandID", DataFormat = global::ProtoBuf.Extended.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int commandID
    {
      get { return _commandID; }
      set { _commandID = value; }
    }

    private long _requestId = default(long);
    [global::ProtoBuf.Extended.ProtoMember(5, IsRequired = false, Name=@"requestId", DataFormat = global::ProtoBuf.Extended.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long requestId
    {
      get { return _requestId; }
      set { _requestId = value; }
    }
    private global::ProtoBuf.Extended.IExtension extensionObject;
   global::ProtoBuf.Extended.IExtension global::ProtoBuf.Extended.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extended.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}