//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MessageEventListResponse.proto
// Note: requires additional types generated from: MessageEventResponse.proto
namespace Alachisoft.NCache.Common.Protobuf
{
  [global::System.Serializable, global::ProtoBuf.Extended.ProtoContract(Name=@"MessageEventListResponse")]
  public partial class MessageEventListResponse : global::ProtoBuf.Extended.IExtensible
  {
    public MessageEventListResponse() {}
    

    private string _topicName = "";
    [global::ProtoBuf.Extended.ProtoMember(1, IsRequired = false, Name=@"topicName", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string topicName
    {
      get { return _topicName; }
      set { _topicName = value; }
    }
    private readonly global::System.Collections.Generic.List<Alachisoft.NCache.Common.Protobuf.MessageEventResponse> _messageEventList = new global::System.Collections.Generic.List<Alachisoft.NCache.Common.Protobuf.MessageEventResponse>();
    [global::ProtoBuf.Extended.ProtoMember(2, Name=@"messageEventList", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    public global::System.Collections.Generic.List<Alachisoft.NCache.Common.Protobuf.MessageEventResponse> messageEventList
    {
      get { return _messageEventList; }
    }
  
    private global::ProtoBuf.Extended.IExtension extensionObject;
   global::ProtoBuf.Extended.IExtension global::ProtoBuf.Extended.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extended.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}