//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: NodeLeftEventResponse.proto
// Note: requires additional types generated from: EventId.proto
namespace Alachisoft.NCache.Common.Protobuf
{
  [global::System.Serializable, global::ProtoBuf.Extended.ProtoContract(Name=@"NodeLeftEventResponse")]
  public partial class NodeLeftEventResponse : global::ProtoBuf.Extended.IExtensible
  {
    public NodeLeftEventResponse() {}
    

    private string _clusterIp = "";
    [global::ProtoBuf.Extended.ProtoMember(1, IsRequired = false, Name=@"clusterIp", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string clusterIp
    {
      get { return _clusterIp; }
      set { _clusterIp = value; }
    }

    private string _clusterPort = "";
    [global::ProtoBuf.Extended.ProtoMember(2, IsRequired = false, Name=@"clusterPort", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string clusterPort
    {
      get { return _clusterPort; }
      set { _clusterPort = value; }
    }

    private string _serverIp = "";
    [global::ProtoBuf.Extended.ProtoMember(3, IsRequired = false, Name=@"serverIp", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string serverIp
    {
      get { return _serverIp; }
      set { _serverIp = value; }
    }

    private string _serverPort = "";
    [global::ProtoBuf.Extended.ProtoMember(4, IsRequired = false, Name=@"serverPort", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string serverPort
    {
      get { return _serverPort; }
      set { _serverPort = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.EventId _eventId = null;
    [global::ProtoBuf.Extended.ProtoMember(5, IsRequired = false, Name=@"eventId", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.EventId eventId
    {
      get { return _eventId; }
      set { _eventId = value; }
    }
    private global::ProtoBuf.Extended.IExtension extensionObject;
   global::ProtoBuf.Extended.IExtension global::ProtoBuf.Extended.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extended.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
