//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Response.proto
// Note: requires additional types generated from: AddResponse.proto
// Note: requires additional types generated from: BulkAddResponse.proto
// Note: requires additional types generated from: BulkGetResponse.proto
// Note: requires additional types generated from: BulkInsertResponse.proto
// Note: requires additional types generated from: BulkRemoveResponse.proto
// Note: requires additional types generated from: ClearResponse.proto
// Note: requires additional types generated from: ContainResponse.proto
// Note: requires additional types generated from: CountResponse.proto
// Note: requires additional types generated from: DisposeResponse.proto
// Note: requires additional types generated from: GetCacheItemResponse.proto
// Note: requires additional types generated from: GetResponse.proto
// Note: requires additional types generated from: GetCompactTypeResponse.proto
// Note: requires additional types generated from: GetEnumeratorResponse.proto
// Note: requires additional types generated from: GetGroupDataResponse.proto
// Note: requires additional types generated from: GetGroupKeysResponse.proto
// Note: requires additional types generated from: GetHashmapResponse.proto
// Note: requires additional types generated from: GetOptimalServerResponse.proto
// Note: requires additional types generated from: GetTagResponse.proto
// Note: requires additional types generated from: GetTypeMapResponse.proto
// Note: requires additional types generated from: InitializeCacheResponse.proto
// Note: requires additional types generated from: InsertReponse.proto
// Note: requires additional types generated from: RaiseCustomEventResponse.proto
// Note: requires additional types generated from: RegisterKeyNotifResponse.proto
// Note: requires additional types generated from: RegisterBulkKeyNotifResponse.proto
// Note: requires additional types generated from: RegisterNotifResponse.proto
// Note: requires additional types generated from: RemoveGroupResponse.proto
// Note: requires additional types generated from: LockResponse.proto
// Note: requires additional types generated from: RemoveResponse.proto
// Note: requires additional types generated from: SearchResponse.proto
// Note: requires additional types generated from: SearchEntriesResponse.proto
// Note: requires additional types generated from: UnlockResponse.proto
// Note: requires additional types generated from: VerifyLockResponse.proto
// Note: requires additional types generated from: IsLockedResponse.proto
// Note: requires additional types generated from: UnregisterBulkKeyNotifResponse.proto
// Note: requires additional types generated from: UnregisterKeyNotifResponse.proto
// Note: requires additional types generated from: HybridBulkResponse.proto
// Note: requires additional types generated from: GetLoggingInfoResponse.proto
// Note: requires additional types generated from: BridgeGetStateTransferInfoResponse.proto
// Note: requires additional types generated from: BridgeGetTransferableKeyListResponse.proto
// Note: requires additional types generated from: BridgeSignalEndOfStateTransferResponse.proto
// Note: requires additional types generated from: BridgeHybridBulkResponse.proto
// Note: requires additional types generated from: BridgeInitResponse.proto
// Note: requires additional types generated from: BridgeSetTransferableKeyListResponse.proto
// Note: requires additional types generated from: Exception.proto
// Note: requires additional types generated from: BridgeFunctionalEventResponse.proto
// Note: requires additional types generated from: CacheClearedEventResponse.proto
// Note: requires additional types generated from: HashmapChangedEventResponse.proto
// Note: requires additional types generated from: CacheStoppedEventResponse.proto
// Note: requires additional types generated from: ConfigModifiedEventResponse.proto
// Note: requires additional types generated from: CustomEventResponse.proto
// Note: requires additional types generated from: ItemAddedEventResponse.proto
// Note: requires additional types generated from: ItemRemovedEventResponse.proto
// Note: requires additional types generated from: ItemUpdatedEventResponse.proto
// Note: requires additional types generated from: LoggingInfoModifiedEventResponse.proto
// Note: requires additional types generated from: NodeJoinedEventResponse.proto
// Note: requires additional types generated from: NodeLeftEventResponse.proto
// Note: requires additional types generated from: QueueFullEventResponse.proto
// Note: requires additional types generated from: AsyncOperationCompletedCallbackResponse.proto
// Note: requires additional types generated from: ItemRemoveCallbackResponse.proto
// Note: requires additional types generated from: ItemUpdatedCallbackResponse.proto
// Note: requires additional types generated from: DSUpdatedCallbackResponse.proto
// Note: requires additional types generated from: BridgeStartStateTransferEventResponse.proto
// Note: requires additional types generated from: BridgeSyncTimeResponse.proto
// Note: requires additional types generated from: HeartBeatResponse.proto
// Note: requires additional types generated from: BridgeHeartBeatReceivedResponse.proto
// Note: requires additional types generated from: RemoveByTagResponse.proto
// Note: requires additional types generated from: BridgeMakeTargetCacheActivePassiveResponse.proto
// Note: requires additional types generated from: CQCallbackResponse.proto
// Note: requires additional types generated from: UnRegisterCQResponse.proto
// Note: requires additional types generated from: RegisterCQResponse.proto
// Note: requires additional types generated from: BridgeStoppedEventResponse.proto
// Note: requires additional types generated from: BridgeClearOperationEnqueuedResponse.proto
// Note: requires additional types generated from: GetKeysByTagResponse.proto
// Note: requires additional types generated from: BulkDeleteResponse.proto
// Note: requires additional types generated from: DeleteResponse.proto
// Note: requires additional types generated from: GetNextChunkResponse.proto
// Note: requires additional types generated from: GetGroupNextChunkResponse.proto
// Note: requires additional types generated from: SearchCQResponse.proto
// Note: requires additional types generated from: SearchEntriesCQResponse.proto
// Note: requires additional types generated from: AddAttributeResponse.proto
// Note: requires additional types generated from: CompactTypeRegisterEvent.proto
// Note: requires additional types generated from: FragmentedResponse.proto
// Note: requires additional types generated from: GetRunningServersResponse.proto
// Note: requires additional types generated from: BulkEventResponse.proto
// Note: requires additional types generated from: SyncEventsResponse.proto
// Note: requires additional types generated from: BlockActivityEventResponse.proto
// Note: requires additional types generated from: UnBlockActivityEventResponse.proto
// Note: requires additional types generated from: RemoveQueryResponse.proto
// Note: requires additional types generated from: DeleteQueryResponse.proto
// Note: requires additional types generated from: GetProductVersionResponse.proto
// Note: requires additional types generated from: GetServerMappingResponse.proto
// Note: requires additional types generated from: BridgeGetReplicatorStatusInfoResponse.proto
// Note: requires additional types generated from: BridgeReplicatorStatusEventResponse.proto
// Note: requires additional types generated from: BridgeRequestStateTransferResponse.proto
// Note: requires additional types generated from: GetCacheBindingResponse.proto
// Note: requires additional types generated from: MapReduceTaskResponse.proto
// Note: requires additional types generated from: TaskCallbackResponse.proto
// Note: requires additional types generated from: TaskCancelResponse.proto
// Note: requires additional types generated from: TaskProgressResponse.proto
// Note: requires additional types generated from: GetRunningTasksResponse.proto
// Note: requires additional types generated from: GetNextRecordResponse.proto
// Note: requires additional types generated from: TaskEnumeratorResponse.proto
// Note: requires additional types generated from: InvokeEntryProcessorResponse.proto
// Note: requires additional types generated from: InquiryRequestResponse.proto
// Note: requires additional types generated from: DisposeReaderResponse.proto
// Note: requires additional types generated from: ExecuteReaderResponse.proto
// Note: requires additional types generated from: GetReaderChunkResponse.proto
// Note: requires additional types generated from: ExecuteReaderCQResponse.proto
// Note: requires additional types generated from: GetExpirationResponse.proto
// Note: requires additional types generated from: PollResponse.proto
// Note: requires additional types generated from: RegisterPollNotifResponse.proto
// Note: requires additional types generated from: PollNotifyEventResponse.proto
// Note: requires additional types generated from: LCDataResponse.proto
// Note: requires additional types generated from: GetConnectedClientsResponse.proto
// Note: requires additional types generated from: TouchResponse.proto
// Note: requires additional types generated from: GetCacheManagementPortResponse.proto
// Note: requires additional types generated from: GetTopicResponse.proto
// Note: requires additional types generated from: SubscribeTopicResponse.proto
// Note: requires additional types generated from: RemoveTopicResponse.proto
// Note: requires additional types generated from: UnSubscribeTopicResponse.proto
// Note: requires additional types generated from: MessagePublishResponse.proto
// Note: requires additional types generated from: GetMessageResponse.proto
// Note: requires additional types generated from: MessageAcknowledgmentResponse.proto
// Note: requires additional types generated from: PingResponse.proto
// Note: requires additional types generated from: OperationModeChangeEventResponse.proto
// Note: requires additional types generated from: MessageCountResponse.proto
// Note: requires additional types generated from: DataTypeResponse.proto
// Note: requires additional types generated from: GetSerializationFormatResponse.proto
// Note: requires additional types generated from: BulkGetCacheItemResponse.proto
// Note: requires additional types generated from: ContainBulkResponse.proto
// Note: requires additional types generated from: SurrogateResponse.proto
// Note: requires additional types generated from: ModuleResponse.proto
namespace Alachisoft.NCache.Common.Protobuf
{
  [global::System.Serializable, global::ProtoBuf.Extended.ProtoContract(Name=@"Response")]
  public partial class Response : global::ProtoBuf.Extended.IExtensible
  {
    public Response() {}
    

    private long _requestId = default(long);
    [global::ProtoBuf.Extended.ProtoMember(1, IsRequired = false, Name=@"requestId", DataFormat = global::ProtoBuf.Extended.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long requestId
    {
      get { return _requestId; }
      set { _requestId = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.Response.Type _responseType = Alachisoft.NCache.Common.Protobuf.Response.Type.ADD;
    [global::ProtoBuf.Extended.ProtoMember(2, IsRequired = false, Name=@"responseType", DataFormat = global::ProtoBuf.Extended.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Alachisoft.NCache.Common.Protobuf.Response.Type.ADD)]
    public Alachisoft.NCache.Common.Protobuf.Response.Type responseType
    {
      get { return _responseType; }
      set { _responseType = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.Exception _exception = null;
    [global::ProtoBuf.Extended.ProtoMember(3, IsRequired = false, Name=@"exception", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.Exception exception
    {
      get { return _exception; }
      set { _exception = value; }
    }
        
    private Alachisoft.NCache.Common.Protobuf.BulkAddResponse _bulkAdd = null;
    [global::ProtoBuf.Extended.ProtoMember(5, IsRequired = false, Name=@"bulkAdd", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.BulkAddResponse bulkAdd
    {
      get { return _bulkAdd; }
      set { _bulkAdd = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.BulkGetResponse _bulkGet = null;
    [global::ProtoBuf.Extended.ProtoMember(6, IsRequired = false, Name=@"bulkGet", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.BulkGetResponse bulkGet
    {
      get { return _bulkGet; }
      set { _bulkGet = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.BulkInsertResponse _bulkInsert = null;
    [global::ProtoBuf.Extended.ProtoMember(7, IsRequired = false, Name=@"bulkInsert", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.BulkInsertResponse bulkInsert
    {
      get { return _bulkInsert; }
      set { _bulkInsert = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.BulkRemoveResponse _bulkRemove = null;
    [global::ProtoBuf.Extended.ProtoMember(8, IsRequired = false, Name=@"bulkRemove", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.BulkRemoveResponse bulkRemove
    {
      get { return _bulkRemove; }
      set { _bulkRemove = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.ContainResponse _contain = null;
    [global::ProtoBuf.Extended.ProtoMember(9, IsRequired = false, Name=@"contain", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.ContainResponse contain
    {
      get { return _contain; }
      set { _contain = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.CountResponse _count = null;
    [global::ProtoBuf.Extended.ProtoMember(10, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.CountResponse count
    {
      get { return _count; }
      set { _count = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.GetCacheItemResponse _getItem = null;
    [global::ProtoBuf.Extended.ProtoMember(11, IsRequired = false, Name=@"getItem", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.GetCacheItemResponse getItem
    {
      get { return _getItem; }
      set { _getItem = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.GetResponse _get = null;
    [global::ProtoBuf.Extended.ProtoMember(12, IsRequired = false, Name=@"get", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.GetResponse get
    {
      get { return _get; }
      set { _get = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.GetCompactTypeResponse _getCompactTypes = null;
    [global::ProtoBuf.Extended.ProtoMember(13, IsRequired = false, Name=@"getCompactTypes", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.GetCompactTypeResponse getCompactTypes
    {
      get { return _getCompactTypes; }
      set { _getCompactTypes = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.GetEnumeratorResponse _getEnum = null;
    [global::ProtoBuf.Extended.ProtoMember(15, IsRequired = false, Name=@"getEnum", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.GetEnumeratorResponse getEnum
    {
      get { return _getEnum; }
      set { _getEnum = value; }
    }

   

  

    private Alachisoft.NCache.Common.Protobuf.GetHashmapResponse _getHashmap = null;
    [global::ProtoBuf.Extended.ProtoMember(18, IsRequired = false, Name=@"getHashmap", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.GetHashmapResponse getHashmap
    {
      get { return _getHashmap; }
      set { _getHashmap = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.GetOptimalServerResponse _getOptimalServer = null;
    [global::ProtoBuf.Extended.ProtoMember(19, IsRequired = false, Name=@"getOptimalServer", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.GetOptimalServerResponse getOptimalServer
    {
      get { return _getOptimalServer; }
      set { _getOptimalServer = value; }
    }


    private Alachisoft.NCache.Common.Protobuf.GetTypeMapResponse _getTypemap = null;
    [global::ProtoBuf.Extended.ProtoMember(21, IsRequired = false, Name=@"getTypemap", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.GetTypeMapResponse getTypemap
    {
      get { return _getTypemap; }
      set { _getTypemap = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.InitializeCacheResponse _initCache = null;
    [global::ProtoBuf.Extended.ProtoMember(22, IsRequired = false, Name=@"initCache", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.InitializeCacheResponse initCache
    {
      get { return _initCache; }
      set { _initCache = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.InsertResponse _insert = null;
    [global::ProtoBuf.Extended.ProtoMember(23, IsRequired = false, Name=@"insert", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.InsertResponse insert
    {
      get { return _insert; }
      set { _insert = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.LockResponse _lockResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(24, IsRequired = false, Name=@"lockResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.LockResponse lockResponse
    {
      get { return _lockResponse; }
      set { _lockResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.VerifyLockResponse _lockVerify = null;
    [global::ProtoBuf.Extended.ProtoMember(25, IsRequired = false, Name=@"lockVerify", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.VerifyLockResponse lockVerify
    {
      get { return _lockVerify; }
      set { _lockVerify = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.RemoveResponse _remove = null;
    [global::ProtoBuf.Extended.ProtoMember(26, IsRequired = false, Name=@"remove", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.RemoveResponse remove
    {
      get { return _remove; }
      set { _remove = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.SearchResponse _search = null;
    [global::ProtoBuf.Extended.ProtoMember(27, IsRequired = false, Name=@"search", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.SearchResponse search
    {
      get { return _search; }
      set { _search = value; }
    }

  
    private Alachisoft.NCache.Common.Protobuf.AddResponse _addResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(29, IsRequired = false, Name=@"addResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.AddResponse addResponse
    {
      get { return _addResponse; }
      set { _addResponse = value; }
    }
        
    private Alachisoft.NCache.Common.Protobuf.ClearResponse _clearResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(31, IsRequired = false, Name=@"clearResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.ClearResponse clearResponse
    {
      get { return _clearResponse; }
      set { _clearResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.DisposeResponse _disposeResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(32, IsRequired = false, Name=@"disposeResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.DisposeResponse disposeResponse
    {
      get { return _disposeResponse; }
      set { _disposeResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.RaiseCustomEventResponse _raiseCustomEventResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(33, IsRequired = false, Name=@"raiseCustomEventResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.RaiseCustomEventResponse raiseCustomEventResponse
    {
      get { return _raiseCustomEventResponse; }
      set { _raiseCustomEventResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.RegisterKeyNotifResponse _registerKeyNotifResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(34, IsRequired = false, Name=@"registerKeyNotifResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.RegisterKeyNotifResponse registerKeyNotifResponse
    {
      get { return _registerKeyNotifResponse; }
      set { _registerKeyNotifResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.RegisterNotifResponse _registerNotifResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(35, IsRequired = false, Name=@"registerNotifResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.RegisterNotifResponse registerNotifResponse
    {
      get { return _registerNotifResponse; }
      set { _registerNotifResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.RemoveGroupResponse _removeGroupResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(36, IsRequired = false, Name=@"removeGroupResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.RemoveGroupResponse removeGroupResponse
    {
      get { return _removeGroupResponse; }
      set { _removeGroupResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.IsLockedResponse _isLockedResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(37, IsRequired = false, Name=@"isLockedResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.IsLockedResponse isLockedResponse
    {
      get { return _isLockedResponse; }
      set { _isLockedResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.UnregisterBulkKeyNotifResponse _unregisterBulkKeyNotifResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(38, IsRequired = false, Name=@"unregisterBulkKeyNotifResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.UnregisterBulkKeyNotifResponse unregisterBulkKeyNotifResponse
    {
      get { return _unregisterBulkKeyNotifResponse; }
      set { _unregisterBulkKeyNotifResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.UnregisterKeyNotifResponse _unregisterKeyNotifResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(39, IsRequired = false, Name=@"unregisterKeyNotifResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.UnregisterKeyNotifResponse unregisterKeyNotifResponse
    {
      get { return _unregisterKeyNotifResponse; }
      set { _unregisterKeyNotifResponse = value; }
    }
           
    private Alachisoft.NCache.Common.Protobuf.GetLoggingInfoResponse _getLoggingInfoResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(41, IsRequired = false, Name=@"getLoggingInfoResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.GetLoggingInfoResponse getLoggingInfoResponse
    {
      get { return _getLoggingInfoResponse; }
      set { _getLoggingInfoResponse = value; }
    }


    private Alachisoft.NCache.Common.Protobuf.AsyncOperationCompletedCallbackResponse _asyncOpCompletedCallback = null;
    [global::ProtoBuf.Extended.ProtoMember(54, IsRequired = false, Name=@"asyncOpCompletedCallback", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.AsyncOperationCompletedCallbackResponse asyncOpCompletedCallback
    {
      get { return _asyncOpCompletedCallback; }
      set { _asyncOpCompletedCallback = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.ItemRemoveCallbackResponse _itemRemovedCallback = null;
    [global::ProtoBuf.Extended.ProtoMember(55, IsRequired = false, Name=@"itemRemovedCallback", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.ItemRemoveCallbackResponse itemRemovedCallback
    {
      get { return _itemRemovedCallback; }
      set { _itemRemovedCallback = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.ItemUpdatedCallbackResponse _itemUpdatedCallback = null;
    [global::ProtoBuf.Extended.ProtoMember(56, IsRequired = false, Name=@"itemUpdatedCallback", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.ItemUpdatedCallbackResponse itemUpdatedCallback
    {
      get { return _itemUpdatedCallback; }
      set { _itemUpdatedCallback = value; }
    }
        

    private Alachisoft.NCache.Common.Protobuf.CacheClearedEventResponse _cacheCleared = null;
    [global::ProtoBuf.Extended.ProtoMember(58, IsRequired = false, Name=@"cacheCleared", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.CacheClearedEventResponse cacheCleared
    {
      get { return _cacheCleared; }
      set { _cacheCleared = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.CacheStoppedEventResponse _cacheStopped = null;
    [global::ProtoBuf.Extended.ProtoMember(59, IsRequired = false, Name=@"cacheStopped", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.CacheStoppedEventResponse cacheStopped
    {
      get { return _cacheStopped; }
      set { _cacheStopped = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.ConfigModifiedEventResponse _configModified = null;
    [global::ProtoBuf.Extended.ProtoMember(60, IsRequired = false, Name=@"configModified", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.ConfigModifiedEventResponse configModified
    {
      get { return _configModified; }
      set { _configModified = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.CustomEventResponse _customEvent = null;
    [global::ProtoBuf.Extended.ProtoMember(61, IsRequired = false, Name=@"customEvent", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.CustomEventResponse customEvent
    {
      get { return _customEvent; }
      set { _customEvent = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.HashmapChangedEventResponse _hashmapChanged = null;
    [global::ProtoBuf.Extended.ProtoMember(62, IsRequired = false, Name=@"hashmapChanged", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.HashmapChangedEventResponse hashmapChanged
    {
      get { return _hashmapChanged; }
      set { _hashmapChanged = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.ItemAddedEventResponse _itemAdded = null;
    [global::ProtoBuf.Extended.ProtoMember(63, IsRequired = false, Name=@"itemAdded", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.ItemAddedEventResponse itemAdded
    {
      get { return _itemAdded; }
      set { _itemAdded = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.ItemRemovedEventResponse _itemRemoved = null;
    [global::ProtoBuf.Extended.ProtoMember(64, IsRequired = false, Name=@"itemRemoved", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.ItemRemovedEventResponse itemRemoved
    {
      get { return _itemRemoved; }
      set { _itemRemoved = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.ItemUpdatedEventResponse _itemUpdated = null;
    [global::ProtoBuf.Extended.ProtoMember(65, IsRequired = false, Name=@"itemUpdated", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.ItemUpdatedEventResponse itemUpdated
    {
      get { return _itemUpdated; }
      set { _itemUpdated = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.LoggingInfoModifiedEventResponse _loggingInfoModified = null;
    [global::ProtoBuf.Extended.ProtoMember(66, IsRequired = false, Name=@"loggingInfoModified", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.LoggingInfoModifiedEventResponse loggingInfoModified
    {
      get { return _loggingInfoModified; }
      set { _loggingInfoModified = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.NodeJoinedEventResponse _nodeJoined = null;
    [global::ProtoBuf.Extended.ProtoMember(67, IsRequired = false, Name=@"nodeJoined", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.NodeJoinedEventResponse nodeJoined
    {
      get { return _nodeJoined; }
      set { _nodeJoined = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.NodeLeftEventResponse _nodeLeft = null;
    [global::ProtoBuf.Extended.ProtoMember(68, IsRequired = false, Name=@"nodeLeft", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.NodeLeftEventResponse nodeLeft
    {
      get { return _nodeLeft; }
      set { _nodeLeft = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.QueueFullEventResponse _queueFullEvent = null;
    [global::ProtoBuf.Extended.ProtoMember(69, IsRequired = false, Name=@"queueFullEvent", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.QueueFullEventResponse queueFullEvent
    {
      get { return _queueFullEvent; }
      set { _queueFullEvent = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.UnlockResponse _unlockResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(70, IsRequired = false, Name=@"unlockResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.UnlockResponse unlockResponse
    {
      get { return _unlockResponse; }
      set { _unlockResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.RegisterBulkKeyNotifResponse _registerBulkKeyNotifResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(71, IsRequired = false, Name=@"registerBulkKeyNotifResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.RegisterBulkKeyNotifResponse registerBulkKeyNotifResponse
    {
      get { return _registerBulkKeyNotifResponse; }
      set { _registerBulkKeyNotifResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.DSUpdatedCallbackResponse _dsUpdateCallbackRespose = null;
    [global::ProtoBuf.Extended.ProtoMember(72, IsRequired = false, Name=@"dsUpdateCallbackRespose", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.DSUpdatedCallbackResponse dsUpdateCallbackRespose
    {
      get { return _dsUpdateCallbackRespose; }
      set { _dsUpdateCallbackRespose = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.HeartBeatResponse _heartBeatResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(75, IsRequired = false, Name=@"heartBeatResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.HeartBeatResponse heartBeatResponse
    {
      get { return _heartBeatResponse; }
      set { _heartBeatResponse = value; }
    }
    private Alachisoft.NCache.Common.Protobuf.BulkDeleteResponse _bulkDeleteResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(85, IsRequired = false, Name=@"bulkDeleteResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.BulkDeleteResponse bulkDeleteResponse
    {
      get { return _bulkDeleteResponse; }
      set { _bulkDeleteResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.DeleteResponse _deleteResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(86, IsRequired = false, Name=@"deleteResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.DeleteResponse deleteResponse
    {
      get { return _deleteResponse; }
      set { _deleteResponse = value; }
    }

    private string _intendedRecipient = "";
    [global::ProtoBuf.Extended.ProtoMember(87, IsRequired = false, Name=@"intendedRecipient", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string intendedRecipient
    {
      get { return _intendedRecipient; }
      set { _intendedRecipient = value; }
    }

    private int _sequenceId = (int)1;
    [global::ProtoBuf.Extended.ProtoMember(88, IsRequired = false, Name=@"sequenceId", DataFormat = global::ProtoBuf.Extended.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)1)]
    public int sequenceId
    {
      get { return _sequenceId; }
      set { _sequenceId = value; }
    }

    private int _numberOfChuncks = (int)1;
    [global::ProtoBuf.Extended.ProtoMember(89, IsRequired = false, Name=@"numberOfChuncks", DataFormat = global::ProtoBuf.Extended.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)1)]
    public int numberOfChuncks
    {
      get { return _numberOfChuncks; }
      set { _numberOfChuncks = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.GetNextChunkResponse _getNextChunkResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(90, IsRequired = false, Name=@"getNextChunkResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.GetNextChunkResponse getNextChunkResponse
    {
      get { return _getNextChunkResponse; }
      set { _getNextChunkResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.GetGroupNextChunkResponse _getGroupNextChunkResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(91, IsRequired = false, Name=@"getGroupNextChunkResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.GetGroupNextChunkResponse getGroupNextChunkResponse
    {
      get { return _getGroupNextChunkResponse; }
      set { _getGroupNextChunkResponse = value; }
    }

  

    private Alachisoft.NCache.Common.Protobuf.AddAttributeResponse _addAttributeResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(94, IsRequired = false, Name=@"addAttributeResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.AddAttributeResponse addAttributeResponse
    {
      get { return _addAttributeResponse; }
      set { _addAttributeResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.CompactTypeRegisterEvent _compactTypeRegisterEvent = null;
    [global::ProtoBuf.Extended.ProtoMember(95, IsRequired = false, Name=@"compactTypeRegisterEvent", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.CompactTypeRegisterEvent compactTypeRegisterEvent
    {
      get { return _compactTypeRegisterEvent; }
      set { _compactTypeRegisterEvent = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.GetRunningServersResponse _getRunningServer = null;
    [global::ProtoBuf.Extended.ProtoMember(97, IsRequired = false, Name=@"getRunningServer", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.GetRunningServersResponse getRunningServer
    {
      get { return _getRunningServer; }
      set { _getRunningServer = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.BulkEventResponse _bulkEventResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(98, IsRequired = false, Name=@"bulkEventResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.BulkEventResponse bulkEventResponse
    {
      get { return _bulkEventResponse; }
      set { _bulkEventResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.SyncEventsResponse _syncEventsResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(99, IsRequired = false, Name=@"syncEventsResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.SyncEventsResponse syncEventsResponse
    {
      get { return _syncEventsResponse; }
      set { _syncEventsResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.BlockActivityEventResponse _blockActivityEvent = null;
    [global::ProtoBuf.Extended.ProtoMember(100, IsRequired = false, Name=@"blockActivityEvent", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.BlockActivityEventResponse blockActivityEvent
    {
      get { return _blockActivityEvent; }
      set { _blockActivityEvent = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.UnBlockActivityEventResponse _unblockActivityEvent = null;
    [global::ProtoBuf.Extended.ProtoMember(101, IsRequired = false, Name=@"unblockActivityEvent", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.UnBlockActivityEventResponse unblockActivityEvent
    {
      get { return _unblockActivityEvent; }
      set { _unblockActivityEvent = value; }
    }


  

    private Alachisoft.NCache.Common.Protobuf.GetProductVersionResponse _getProductVersionResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(104, IsRequired = false, Name=@"getProductVersionResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.GetProductVersionResponse getProductVersionResponse
    {
      get { return _getProductVersionResponse; }
      set { _getProductVersionResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.FragmentedResponse _getResponseFragment = null;
    [global::ProtoBuf.Extended.ProtoMember(108, IsRequired = false, Name=@"getResponseFragment", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.FragmentedResponse getResponseFragment
    {
      get { return _getResponseFragment; }
      set { _getResponseFragment = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.GetServerMappingResponse _getServerMappingResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(109, IsRequired = false, Name=@"getServerMappingResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.GetServerMappingResponse getServerMappingResponse
    {
      get { return _getServerMappingResponse; }
      set { _getServerMappingResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.InquiryRequestResponse _inquiryRequestResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(110, IsRequired = false, Name=@"inquiryRequestResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.InquiryRequestResponse inquiryRequestResponse
    {
      get { return _inquiryRequestResponse; }
      set { _inquiryRequestResponse = value; }
    }

    private int _commandID = default(int);
    [global::ProtoBuf.Extended.ProtoMember(111, IsRequired = false, Name=@"commandID", DataFormat = global::ProtoBuf.Extended.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int commandID
    {
      get { return _commandID; }
      set { _commandID = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.GetCacheBindingResponse _getCacheBindingResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(112, IsRequired = false, Name=@"getCacheBindingResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.GetCacheBindingResponse getCacheBindingResponse
    {
      get { return _getCacheBindingResponse; }
      set { _getCacheBindingResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.DisposeReaderResponse _disposeReaderResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(121, IsRequired = false, Name=@"disposeReaderResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.DisposeReaderResponse disposeReaderResponse
    {
      get { return _disposeReaderResponse; }
      set { _disposeReaderResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.ExecuteReaderResponse _executeReaderResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(122, IsRequired = false, Name=@"executeReaderResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.ExecuteReaderResponse executeReaderResponse
    {
      get { return _executeReaderResponse; }
      set { _executeReaderResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.GetReaderChunkResponse _getReaderChunkResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(123, IsRequired = false, Name=@"getReaderChunkResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.GetReaderChunkResponse getReaderChunkResponse
    {
      get { return _getReaderChunkResponse; }
      set { _getReaderChunkResponse = value; }
    }



    private Alachisoft.NCache.Common.Protobuf.LCDataResponse _LcDataResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(126, IsRequired = false, Name=@"LcDataResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.LCDataResponse LcDataResponse
    {
      get { return _LcDataResponse; }
      set { _LcDataResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.PollResponse _pollResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(128, IsRequired = false, Name=@"pollResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.PollResponse pollResponse
    {
      get { return _pollResponse; }
      set { _pollResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.RegisterPollNotifResponse _registerPollNotifResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(129, IsRequired = false, Name=@"registerPollNotifResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.RegisterPollNotifResponse registerPollNotifResponse
    {
      get { return _registerPollNotifResponse; }
      set { _registerPollNotifResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.PollNotifyEventResponse _pollNotifyEventResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(130, IsRequired = false, Name=@"pollNotifyEventResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.PollNotifyEventResponse pollNotifyEventResponse
    {
      get { return _pollNotifyEventResponse; }
      set { _pollNotifyEventResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.GetConnectedClientsResponse _getConnectedClientsResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(131, IsRequired = false, Name=@"getConnectedClientsResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.GetConnectedClientsResponse getConnectedClientsResponse
    {
      get { return _getConnectedClientsResponse; }
      set { _getConnectedClientsResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.TouchResponse _touchResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(132, IsRequired = false, Name=@"touchResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.TouchResponse touchResponse
    {
      get { return _touchResponse; }
      set { _touchResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.GetCacheManagementPortResponse _getCacheManagementPortResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(133, IsRequired = false, Name=@"getCacheManagementPortResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.GetCacheManagementPortResponse getCacheManagementPortResponse
    {
      get { return _getCacheManagementPortResponse; }
      set { _getCacheManagementPortResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.GetTopicResponse _getTopicResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(134, IsRequired = false, Name=@"getTopicResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.GetTopicResponse getTopicResponse
    {
      get { return _getTopicResponse; }
      set { _getTopicResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.SubscribeTopicResponse _subscribeTopicResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(135, IsRequired = false, Name=@"subscribeTopicResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.SubscribeTopicResponse subscribeTopicResponse
    {
      get { return _subscribeTopicResponse; }
      set { _subscribeTopicResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.RemoveTopicResponse _removeTopicResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(136, IsRequired = false, Name=@"removeTopicResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.RemoveTopicResponse removeTopicResponse
    {
      get { return _removeTopicResponse; }
      set { _removeTopicResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.UnSubscribeTopicResponse _unSubscribeTopicResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(137, IsRequired = false, Name=@"unSubscribeTopicResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.UnSubscribeTopicResponse unSubscribeTopicResponse
    {
      get { return _unSubscribeTopicResponse; }
      set { _unSubscribeTopicResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.MessagePublishResponse _messagePublishResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(138, IsRequired = false, Name=@"messagePublishResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.MessagePublishResponse messagePublishResponse
    {
      get { return _messagePublishResponse; }
      set { _messagePublishResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.GetMessageResponse _getMessageResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(139, IsRequired = false, Name=@"getMessageResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.GetMessageResponse getMessageResponse
    {
      get { return _getMessageResponse; }
      set { _getMessageResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.MessageAcknowledgmentResponse _messageAcknowledgmentResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(140, IsRequired = false, Name=@"messageAcknowledgmentResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.MessageAcknowledgmentResponse messageAcknowledgmentResponse
    {
      get { return _messageAcknowledgmentResponse; }
      set { _messageAcknowledgmentResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.PingResponse _pingResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(141, IsRequired = false, Name=@"pingResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.PingResponse pingResponse
    {
      get { return _pingResponse; }
      set { _pingResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.OperationModeChangeEventResponse _operationModeChangeEventResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(142, IsRequired = false, Name=@"operationModeChangeEventResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.OperationModeChangeEventResponse operationModeChangeEventResponse
    {
      get { return _operationModeChangeEventResponse; }
      set { _operationModeChangeEventResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.MessageCountResponse _messageCountResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(143, IsRequired = false, Name=@"messageCountResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.MessageCountResponse messageCountResponse
    {
      get { return _messageCountResponse; }
      set { _messageCountResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.GetSerializationFormatResponse _getSerializationFormatResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(145, IsRequired = false, Name=@"getSerializationFormatResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.GetSerializationFormatResponse getSerializationFormatResponse
    {
      get { return _getSerializationFormatResponse; }
      set { _getSerializationFormatResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.BulkGetCacheItemResponse _bulkGetCacheItem = null;
    [global::ProtoBuf.Extended.ProtoMember(146, IsRequired = false, Name=@"bulkGetCacheItem", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.BulkGetCacheItemResponse bulkGetCacheItem
    {
      get { return _bulkGetCacheItem; }
      set { _bulkGetCacheItem = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.ContainBulkResponse _containBulkResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(147, IsRequired = false, Name=@"containBulkResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.ContainBulkResponse containBulkResponse
    {
      get { return _containBulkResponse; }
      set { _containBulkResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.SurrogateResponse _surrogateResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(149, IsRequired = false, Name=@"surrogateResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.SurrogateResponse surrogateResponse
    {
      get { return _surrogateResponse; }
      set { _surrogateResponse = value; }
    }

    private Alachisoft.NCache.Common.Protobuf.GetServerIdentityResponse _getServerIdentityResponse = null;
    [global::ProtoBuf.Extended.ProtoMember(157, IsRequired = false, Name = @"getServerIdentityResponse", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Alachisoft.NCache.Common.Protobuf.GetServerIdentityResponse getServerIdentityResponse
        {
        get { return _getServerIdentityResponse; }
        set { _getServerIdentityResponse = value; }
    }

        [global::ProtoBuf.Extended.ProtoContract(Name=@"Type")]
    public enum Type
    {
      [global::ProtoBuf.Extended.ProtoEnum(Name = @"LEGACY_RESPONSE", Value = 0)]
      LEGACY_RESPONSE = 0,

      [global::ProtoBuf.Extended.ProtoEnum(Name=@"ADD", Value=1)]
      ADD = 1,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"ADD_BULK", Value=4)]
      ADD_BULK = 4,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"GET_BULK", Value=5)]
      GET_BULK = 5,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"INSERT_BULK", Value=6)]
      INSERT_BULK = 6,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"REMOVE_BULK", Value=7)]
      REMOVE_BULK = 7,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"CLEAR", Value=8)]
      CLEAR = 8,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"CONTAINS", Value=9)]
      CONTAINS = 9,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"COUNT", Value=10)]
      COUNT = 10,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"DISPOSE", Value=11)]
      DISPOSE = 11,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"GET_CACHE_ITEM", Value=12)]
      GET_CACHE_ITEM = 12,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"GET", Value=13)]
      GET = 13,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"GET_COMPACT_TYPES", Value=14)]
      GET_COMPACT_TYPES = 14,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"GET_ENUMERATOR", Value=15)]
      GET_ENUMERATOR = 15,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"GET_HASHMAP", Value=17)]
      GET_HASHMAP = 17,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"GET_OPTIMAL_SERVER", Value=18)]
      GET_OPTIMAL_SERVER = 18,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"GET_TYPEINFO_MAP", Value=20)]
      GET_TYPEINFO_MAP = 20,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"INIT", Value=21)]
      INIT = 21,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"INSERT", Value=22)]
      INSERT = 22,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"RAISE_CUSTOM_EVENT", Value=23)]
      RAISE_CUSTOM_EVENT = 23,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"REGISTER_KEY_NOTIF", Value=24)]
      REGISTER_KEY_NOTIF = 24,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"REGISTER_NOTIF", Value=25)]
      REGISTER_NOTIF = 25,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"REMOVE", Value=26)]
      REMOVE = 26,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"REMOVE_GROUP", Value=27)]
      REMOVE_GROUP = 27,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"SEARCH", Value=28)]
      SEARCH = 28,
            
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"LOCK", Value=30)]
      LOCK = 30,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"UNLOCK", Value=31)]
      UNLOCK = 31,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"ISLOCKED", Value=32)]
      ISLOCKED = 32,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"LOCK_VERIFY", Value=33)]
      LOCK_VERIFY = 33,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"UNREGISTER_KEY_NOTIF", Value=34)]
      UNREGISTER_KEY_NOTIF = 34,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"UNREGISTER_BULK_KEY_NOTIF", Value=35)]
      UNREGISTER_BULK_KEY_NOTIF = 35,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"REGISTER_BULK_KEY_NOTIF", Value=36)]
      REGISTER_BULK_KEY_NOTIF = 36,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"GET_LOGGING_INFO", Value=38)]
      GET_LOGGING_INFO = 38,
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"SEARCH_ENTRIES", Value=51)]
      SEARCH_ENTRIES = 51,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"EXCEPTION", Value=52)]
      EXCEPTION = 52,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"ASYNC_OP_COMPLETED_CALLBACK", Value=53)]
      ASYNC_OP_COMPLETED_CALLBACK = 53,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"ITEM_REMOVED_CALLBACK", Value=54)]
      ITEM_REMOVED_CALLBACK = 54,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"ITEM_UPDATED_CALLBACK", Value=55)]
      ITEM_UPDATED_CALLBACK = 55,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"CACHE_CLEARED_EVENT", Value=57)]
      CACHE_CLEARED_EVENT = 57,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"CACHE_STOPPED_EVENT", Value=58)]
      CACHE_STOPPED_EVENT = 58,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"CONFIG_MODIFIED_EVENT", Value=59)]
      CONFIG_MODIFIED_EVENT = 59,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"CUSTOM_EVENT", Value=60)]
      CUSTOM_EVENT = 60,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"HASHMAP_CHANGED_EVENT", Value=61)]
      HASHMAP_CHANGED_EVENT = 61,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"ITEM_ADDED_EVENT", Value=62)]
      ITEM_ADDED_EVENT = 62,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"ITEM_REMOVED_EVENT", Value=63)]
      ITEM_REMOVED_EVENT = 63,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"ITEM_UPDATED_EVENT", Value=64)]
      ITEM_UPDATED_EVENT = 64,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"LOGGING_INFO_MODIFIED_EVENT", Value=65)]
      LOGGING_INFO_MODIFIED_EVENT = 65,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"NODE_JOINED_EVENT", Value=66)]
      NODE_JOINED_EVENT = 66,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"NODE_LEFT_EVENT", Value=67)]
      NODE_LEFT_EVENT = 67,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"QUEUE_FULL_EVENT", Value=68)]
      QUEUE_FULL_EVENT = 68,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"DS_UPDATE_CALLBACK", Value=69)]
      DS_UPDATE_CALLBACK = 69,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"HEART_BEAT", Value=72)]
      HEART_BEAT = 72,
   
         [global::ProtoBuf.Extended.ProtoEnum(Name=@"CQ_CALLBACK", Value=76)]
      CQ_CALLBACK = 76,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"UNREGISTER_CQ", Value=77)]
      UNREGISTER_CQ = 77,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"REGISTER_CQ", Value=78)]
      REGISTER_CQ = 78,
           
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"DELETE_BULK", Value=82)]
      DELETE_BULK = 82,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"DELETE", Value=83)]
      DELETE = 83,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"GET_NEXT_CHUNK", Value=84)]
      GET_NEXT_CHUNK = 84,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"GET_GROUP_NEXT_CHUNK", Value=85)]
      GET_GROUP_NEXT_CHUNK = 85,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"SEARCH_CQ", Value=86)]
      SEARCH_CQ = 86,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"SEARCH_ENTRIES_CQ", Value=87)]
      SEARCH_ENTRIES_CQ = 87,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"ADD_ATTRIBUTE", Value=88)]
      ADD_ATTRIBUTE = 88,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"COMPACT_TYPE_REGISTER_EVENT", Value=89)]
      COMPACT_TYPE_REGISTER_EVENT = 89,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"GET_RUNNING_SERVERS", Value=91)]
      GET_RUNNING_SERVERS = 91,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"BULK_EVENT", Value=92)]
      BULK_EVENT = 92,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"SYNC_EVENTS", Value=93)]
      SYNC_EVENTS = 93,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"BLOCK_ACTIVITY", Value=94)]
      BLOCK_ACTIVITY = 94,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"UNBLOCK_ACTIVITY", Value=95)]
      UNBLOCK_ACTIVITY = 95,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"REMOVE_QUERY", Value=96)]
      REMOVE_QUERY = 96,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"DELETE_QUERY", Value=97)]
      DELETE_QUERY = 97,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"GET_PRODUCT_VERSION", Value=98)]
      GET_PRODUCT_VERSION = 98,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"RESPONSE_FRAGMENT", Value=102)]
      RESPONSE_FRAGMENT = 102,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"INQUIRY_REQUEST_RESPONSE", Value=103)]
      INQUIRY_REQUEST_RESPONSE = 103,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"GET_SERVER_MAPPING", Value=104)]
      GET_SERVER_MAPPING = 104,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"GET_CACHE_BINDING", Value=105)]
      GET_CACHE_BINDING = 105,
    
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"DISPOSE_READER", Value=114)]
      DISPOSE_READER = 114,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"EXECUTE_READER", Value=115)]
      EXECUTE_READER = 115,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"GET_READER_CHUNK", Value=116)]
      GET_READER_CHUNK = 116,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"EXECUTE_READER_CQ", Value=117)]
      EXECUTE_READER_CQ = 117,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"EXPIRATION_RESPONSE", Value=118)]
      EXPIRATION_RESPONSE = 118,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"LC_DATA", Value=119)]
      LC_DATA = 119,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"POLL", Value=121)]
      POLL = 121,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"REGISTER_POLL_NOTIF", Value=122)]
      REGISTER_POLL_NOTIF = 122,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"POLL_NOTIFY_CALLBACK", Value=123)]
      POLL_NOTIFY_CALLBACK = 123,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"GET_CONNECTED_CLIENTS", Value=124)]
      GET_CONNECTED_CLIENTS = 124,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"CLIENT_CONNECTIVITY_EVENT", Value=125)]
      CLIENT_CONNECTIVITY_EVENT = 125,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"TOUCH", Value=126)]
      TOUCH = 126,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"GET_CACHE_MANAGEMENT_PORT", Value=127)]
      GET_CACHE_MANAGEMENT_PORT = 127,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"GET_TOPIC", Value=128)]
      GET_TOPIC = 128,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"SUBSCRIBE_TOPIC", Value=129)]
      SUBSCRIBE_TOPIC = 129,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"REMOVE_TOPIC", Value=130)]
      REMOVE_TOPIC = 130,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"UNSUBSCRIBE_TOPIC", Value=131)]
      UNSUBSCRIBE_TOPIC = 131,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"MESSAGE_PUBLISH", Value=132)]
      MESSAGE_PUBLISH = 132,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"GET_MESSAGE", Value=133)]
      GET_MESSAGE = 133,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"MESSAGE_ACKNOWLEDGEMENT", Value=134)]
      MESSAGE_ACKNOWLEDGEMENT = 134,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"PING", Value=135)]
      PING = 135,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"OPERATIONCHANGEDEVNET", Value=136)]
      OPERATIONCHANGEDEVNET = 136,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"MESSAGE_COUNT", Value=137)]
      MESSAGE_COUNT = 137,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"GET_SERIALIZATION_FORMAT", Value=139)]
      GET_SERIALIZATION_FORMAT = 139,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"BULK_GET_CACHEITEM", Value=140)]
      BULK_GET_CACHEITEM = 140,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"CONTAINS_BULK", Value=141)]
      CONTAINS_BULK = 141,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"MODULE", Value=142)]
      MODULE = 142,
            
      [global::ProtoBuf.Extended.ProtoEnum(Name=@"SURROGATE", Value=143)]
      SURROGATE = 143,

    [global::ProtoBuf.Extended.ProtoEnum(Name = @"GET_SERVER_IDENTITY", Value = 148)]
    GET_SERVER_IDENTITY = 148
        }


  
    private global::ProtoBuf.Extended.IExtension extensionObject;
   global::ProtoBuf.Extended.IExtension global::ProtoBuf.Extended.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extended.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}