//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SubscriptionIdRecepientList.proto
namespace Alachisoft.NCache.Common.Protobuf
{
  [global::System.Serializable, global::ProtoBuf.Extended.ProtoContract(Name=@"SubscriptionIdRecepientList")]
  public partial class SubscriptionIdRecepientList : global::ProtoBuf.Extended.IExtensible
  {
    public SubscriptionIdRecepientList() {}
    

    private string _subscriptionName = "";
    [global::ProtoBuf.Extended.ProtoMember(1, IsRequired = false, Name=@"subscriptionName", DataFormat = global::ProtoBuf.Extended.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string subscriptionName
    {
      get { return _subscriptionName; }
      set { _subscriptionName = value; }
    }

    private int _policy = default(int);
    [global::ProtoBuf.Extended.ProtoMember(2, IsRequired = false, Name=@"policy", DataFormat = global::ProtoBuf.Extended.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int policy
    {
      get { return _policy; }
      set { _policy = value; }
    }
    private global::ProtoBuf.Extended.IExtension extensionObject;
   global::ProtoBuf.Extended.IExtension global::ProtoBuf.Extended.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extended.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}