//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alachisoft.NCache.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ExceptionsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alachisoft.NCache.Common.Resources.ExceptionsResource", typeof(ExceptionsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster can not be started on the given server port. The port might be already in use..
        /// </summary>
        internal static string EM001 {
            get {
                return ResourceManager.GetString("EM001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local address is null.
        /// </summary>
        internal static string EM002 {
            get {
                return ResourceManager.GetString("EM002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message can only contain an Array of messages or a ISerializable object.
        /// </summary>
        internal static string EM004 {
            get {
                return ResourceManager.GetString("EM004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index out of bounds.
        /// </summary>
        internal static string EM005 {
            get {
                return ResourceManager.GetString("EM005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified object for message is not serializable.
        /// </summary>
        internal static string EM006 {
            get {
                return ResourceManager.GetString("EM006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid BindToIP address specified.
        /// </summary>
        internal static string EM007 {
            get {
                return ResourceManager.GetString("EM007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid initial memebers list.
        /// </summary>
        internal static string EM008 {
            get {
                return ResourceManager.GetString("EM008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type.
        /// </summary>
        internal static string EM009 {
            get {
                return ResourceManager.GetString("EM009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmd.
        /// </summary>
        internal static string EM010 {
            get {
                return ResourceManager.GetString("EM010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval().
        /// </summary>
        internal static string EM011 {
            get {
                return ResourceManager.GetString("EM011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to socket closed.
        /// </summary>
        internal static string EM012 {
            get {
                return ResourceManager.GetString("EM012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hints.
        /// </summary>
        internal static string EM013 {
            get {
                return ResourceManager.GetString("EM013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to properties.
        /// </summary>
        internal static string EM014 {
            get {
                return ResourceManager.GetString("EM014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cache instance defined.
        /// </summary>
        internal static string EM015 {
            get {
                return ResourceManager.GetString("EM015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connection or query string is null.
        /// </summary>
        internal static string EM016 {
            get {
                return ResourceManager.GetString("EM016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing configuration attribute &apos;cache&apos;.
        /// </summary>
        internal static string EM017 {
            get {
                return ResourceManager.GetString("EM017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing configuration attribute &apos;class&apos;.
        /// </summary>
        internal static string EM018 {
            get {
                return ResourceManager.GetString("EM018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing configuration section &apos;cache-classes&apos;.
        /// </summary>
        internal static string EM019 {
            get {
                return ResourceManager.GetString("EM019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find cache class &apos;.
        /// </summary>
        internal static string EM020 {
            get {
                return ResourceManager.GetString("EM020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find the type of cache, invalid configuration for cache class &apos;.
        /// </summary>
        internal static string EM021 {
            get {
                return ResourceManager.GetString("EM021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your license for using NCache has expired. Please contact sales@alachisoft.com for further terms and conditions..
        /// </summary>
        internal static string EM022 {
            get {
                return ResourceManager.GetString("EM022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified cache class &apos;.
        /// </summary>
        internal static string EM023 {
            get {
                return ResourceManager.GetString("EM023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backing source not available. Verify backing source settings.
        /// </summary>
        internal static string EM024 {
            get {
                return ResourceManager.GetString("EM024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key.
        /// </summary>
        internal static string EM025 {
            get {
                return ResourceManager.GetString("EM025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key is not serializable.
        /// </summary>
        internal static string EM026 {
            get {
                return ResourceManager.GetString("EM026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group.
        /// </summary>
        internal static string EM027 {
            get {
                return ResourceManager.GetString("EM027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keys.
        /// </summary>
        internal static string EM028 {
            get {
                return ResourceManager.GetString("EM028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.
        /// </summary>
        internal static string EM029 {
            get {
                return ResourceManager.GetString("EM029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value is not serializable.
        /// </summary>
        internal static string EM030 {
            get {
                return ResourceManager.GetString("EM030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expiryHint is not serializable.
        /// </summary>
        internal static string EM031 {
            get {
                return ResourceManager.GetString("EM031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to evictionHint is not serializable.
        /// </summary>
        internal static string EM032 {
            get {
                return ResourceManager.GetString("EM032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notifId is not serializable.
        /// </summary>
        internal static string EM033 {
            get {
                return ResourceManager.GetString("EM033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data is not serializable.
        /// </summary>
        internal static string EM034 {
            get {
                return ResourceManager.GetString("EM034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expiryHint is not not serializable.
        /// </summary>
        internal static string EM035 {
            get {
                return ResourceManager.GetString("EM035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic operation failure; not enough information is available..
        /// </summary>
        internal static string EM036 {
            get {
                return ResourceManager.GetString("EM036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cache is full and not enough items could be evicted..
        /// </summary>
        internal static string EM037 {
            get {
                return ResourceManager.GetString("EM037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified key already exists..
        /// </summary>
        internal static string EM038 {
            get {
                return ResourceManager.GetString("EM038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items.
        /// </summary>
        internal static string EM039 {
            get {
                return ResourceManager.GetString("EM039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keys count is not equals to values count.
        /// </summary>
        internal static string EM040 {
            get {
                return ResourceManager.GetString("EM040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group must be specified for Sub Group.
        /// </summary>
        internal static string EM041 {
            get {
                return ResourceManager.GetString("EM041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to query.
        /// </summary>
        internal static string EM042 {
            get {
                return ResourceManager.GetString("EM042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect query format.
        /// </summary>
        internal static string EM043 {
            get {
                return ResourceManager.GetString("EM043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys count can not be zero.
        /// </summary>
        internal static string EM044 {
            get {
                return ResourceManager.GetString("EM044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method or operation is not implemented..
        /// </summary>
        internal static string EM045 {
            get {
                return ResourceManager.GetString("EM045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read through provider returned an object that is not serializable..
        /// </summary>
        internal static string EM046 {
            get {
                return ResourceManager.GetString("EM046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed to synchronize with data source.
        /// </summary>
        internal static string EM047 {
            get {
                return ResourceManager.GetString("EM047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing assembly name for write-thru option.
        /// </summary>
        internal static string EM048 {
            get {
                return ResourceManager.GetString("EM048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing class name for write-thru option.
        /// </summary>
        internal static string EM049 {
            get {
                return ResourceManager.GetString("EM049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The class specified in write-thru does not implement IDatasourceWriter.
        /// </summary>
        internal static string EM050 {
            get {
                return ResourceManager.GetString("EM050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing assembly name for read-thru option.
        /// </summary>
        internal static string EM051 {
            get {
                return ResourceManager.GetString("EM051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing class name for read-thru option.
        /// </summary>
        internal static string EM052 {
            get {
                return ResourceManager.GetString("EM052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The class specified in read-thru does not implement IDatasourceReader.
        /// </summary>
        internal static string EM053 {
            get {
                return ResourceManager.GetString("EM053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect query format \&apos;*\&apos;.
        /// </summary>
        internal static string EM054 {
            get {
                return ResourceManager.GetString("EM054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax Error !.
        /// </summary>
        internal static string EM055 {
            get {
                return ResourceManager.GetString("EM055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No attribute-index are defined.
        /// </summary>
        internal static string EM056 {
            get {
                return ResourceManager.GetString("EM056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect query format \&apos;.
        /// </summary>
        internal static string EM057 {
            get {
                return ResourceManager.GetString("EM057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index is not defined on attribute &apos;.
        /// </summary>
        internal static string EM058 {
            get {
                return ResourceManager.GetString("EM058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cache.
        /// </summary>
        internal static string EM059 {
            get {
                return ResourceManager.GetString("EM059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operation failed because the group member was suspected.
        /// </summary>
        internal static string EM060 {
            get {
                return ResourceManager.GetString("EM060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operation timed out.
        /// </summary>
        internal static string EM061 {
            get {
                return ResourceManager.GetString("EM061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid or non-local class specified in partitioned cache.
        /// </summary>
        internal static string EM062 {
            get {
                return ResourceManager.GetString("EM062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data affinity conflict.
        /// </summary>
        internal static string EM063 {
            get {
                return ResourceManager.GetString("EM063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the dependency keys does not exist..
        /// </summary>
        internal static string EM064 {
            get {
                return ResourceManager.GetString("EM064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No target node available to accommodate the data..
        /// </summary>
        internal static string EM065 {
            get {
                return ResourceManager.GetString("EM065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No servers available to process request.
        /// </summary>
        internal static string EM066 {
            get {
                return ResourceManager.GetString("EM066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified dependency is non routable.
        /// </summary>
        internal static string EM067 {
            get {
                return ResourceManager.GetString("EM067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data group of the inserted item does not match the existing item&apos;s data group.
        /// </summary>
        internal static string EM068 {
            get {
                return ResourceManager.GetString("EM068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting up key depenedncy..
        /// </summary>
        internal static string EM069 {
            get {
                return ResourceManager.GetString("EM069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am no more the owner of this bucket.
        /// </summary>
        internal static string EM070 {
            get {
                return ResourceManager.GetString("EM070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing configuration option &apos;storage&apos;.
        /// </summary>
        internal static string EM071 {
            get {
                return ResourceManager.GetString("EM071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid or non-local cache class specified in composite cache.
        /// </summary>
        internal static string EM072 {
            get {
                return ResourceManager.GetString("EM072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slidingExpiration.
        /// </summary>
        internal static string EM073 {
            get {
                return ResourceManager.GetString("EM073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find the type of cache, invalid configuration for cache class.
        /// </summary>
        internal static string EM074 {
            get {
                return ResourceManager.GetString("EM074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find channel properties.
        /// </summary>
        internal static string EM075 {
            get {
                return ResourceManager.GetString("EM075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid EOF.
        /// </summary>
        internal static string EM076 {
            get {
                return ResourceManager.GetString("EM076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid property string, un-matched paranthesis.
        /// </summary>
        internal static string EM077 {
            get {
                return ResourceManager.GetString("EM077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid property string, ) misplaced.
        /// </summary>
        internal static string EM078 {
            get {
                return ResourceManager.GetString("EM078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid property string, ) unexpected.
        /// </summary>
        internal static string EM079 {
            get {
                return ResourceManager.GetString("EM079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid property string, key following a bad token.
        /// </summary>
        internal static string EM080 {
            get {
                return ResourceManager.GetString("EM080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid property string, value following a bad token.
        /// </summary>
        internal static string EM081 {
            get {
                return ResourceManager.GetString("EM081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid property string.
        /// </summary>
        internal static string EM082 {
            get {
                return ResourceManager.GetString("EM082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while reading configuration.
        /// </summary>
        internal static string EM083 {
            get {
                return ResourceManager.GetString("EM083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified cache config. section &apos;.
        /// </summary>
        internal static string EM084 {
            get {
                return ResourceManager.GetString("EM084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Authentication Code.
        /// </summary>
        internal static string EM085 {
            get {
                return ResourceManager.GetString("EM085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License not verified..
        /// </summary>
        internal static string EM086 {
            get {
                return ResourceManager.GetString("EM086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EvaluationLicense information is either missing or corrupted..
        /// </summary>
        internal static string EM087 {
            get {
                return ResourceManager.GetString("EM087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your library has expired the evaluation period of.
        /// </summary>
        internal static string EM088 {
            get {
                return ResourceManager.GetString("EM088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can not be registered with compact framework.
        /// </summary>
        internal static string EM089 {
            get {
                return ResourceManager.GetString("EM089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize.
        /// </summary>
        internal static string EM090 {
            get {
                return ResourceManager.GetString("EM090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot set both sliding and absolute expirations on the same cached item..
        /// </summary>
        internal static string EM091 {
            get {
                return ResourceManager.GetString("EM091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dependencies.
        /// </summary>
        internal static string EM092 {
            get {
                return ResourceManager.GetString("EM092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key cannot be empty string.
        /// </summary>
        internal static string EM093 {
            get {
                return ResourceManager.GetString("EM093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable extracting query information from user object..
        /// </summary>
        internal static string EM094 {
            get {
                return ResourceManager.GetString("EM094", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dependency is not serializable.
        /// </summary>
        internal static string EM095 {
            get {
                return ResourceManager.GetString("EM095", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to syncDependency.
        /// </summary>
        internal static string EM096 {
            get {
                return ResourceManager.GetString("EM096", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache is not initialized.
        /// </summary>
        internal static string EM097 {
            get {
                return ResourceManager.GetString("EM097", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group must be specified for sub group.
        /// </summary>
        internal static string EM098 {
            get {
                return ResourceManager.GetString("EM098", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keys count is not equals to items count.
        /// </summary>
        internal static string EM099 {
            get {
                return ResourceManager.GetString("EM099", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no key present in keys array.
        /// </summary>
        internal static string EM100 {
            get {
                return ResourceManager.GetString("EM100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items[.
        /// </summary>
        internal static string EM101 {
            get {
                return ResourceManager.GetString("EM101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fileName.
        /// </summary>
        internal static string EM102 {
            get {
                return ResourceManager.GetString("EM102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fileName cannot be an empty string.
        /// </summary>
        internal static string EM103 {
            get {
                return ResourceManager.GetString("EM103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fileNames array must have atleast one file name.
        /// </summary>
        internal static string EM104 {
            get {
                return ResourceManager.GetString("EM104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fileName cannot be empty string.
        /// </summary>
        internal static string EM105 {
            get {
                return ResourceManager.GetString("EM105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cacheKey.
        /// </summary>
        internal static string EM106 {
            get {
                return ResourceManager.GetString("EM106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cacheKey cannot be empty string.
        /// </summary>
        internal static string EM107 {
            get {
                return ResourceManager.GetString("EM107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cacheId.
        /// </summary>
        internal static string EM108 {
            get {
                return ResourceManager.GetString("EM108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cacheId cannot be an empty string.
        /// </summary>
        internal static string EM109 {
            get {
                return ResourceManager.GetString("EM109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No server is available to process the request.
        /// </summary>
        internal static string EM110 {
            get {
                return ResourceManager.GetString("EM110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session state is not available in this context..
        /// </summary>
        internal static string EM111 {
            get {
                return ResourceManager.GetString("EM111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing installation folder information.
        /// </summary>
        internal static string EM112 {
            get {
                return ResourceManager.GetString("EM112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while reading client.ncconf..
        /// </summary>
        internal static string EM113 {
            get {
                return ResourceManager.GetString("EM113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid XmlNode \&apos;.
        /// </summary>
        internal static string EM114 {
            get {
                return ResourceManager.GetString("EM114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input endIndex is not in correct format..
        /// </summary>
        internal static string EM115 {
            get {
                return ResourceManager.GetString("EM115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot set both sliding and absolute expirations on the same cached item.
        /// </summary>
        internal static string EM116 {
            get {
                return ResourceManager.GetString("EM116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection with server lost.
        /// </summary>
        internal static string EM117 {
            get {
                return ResourceManager.GetString("EM117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string EM118 {
            get {
                return ResourceManager.GetString("EM118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Client.ncconf&apos; not found or does not contain server information.
        /// </summary>
        internal static string EM119 {
            get {
                return ResourceManager.GetString("EM119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to a remote server is not allowed in this edition of NCache.
        /// </summary>
        internal static string EM120 {
            get {
                return ResourceManager.GetString("EM120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ncache-server-port missing in client confiugration.
        /// </summary>
        internal static string EM121 {
            get {
                return ResourceManager.GetString("EM121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application.
        /// </summary>
        internal static string EM122 {
            get {
                return ResourceManager.GetString("EM122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data.
        /// </summary>
        internal static string EM123 {
            get {
                return ResourceManager.GetString("EM123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache is not running. For more information see Application Log..
        /// </summary>
        internal static string EM124 {
            get {
                return ResourceManager.GetString("EM124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration; missing &apos;web-cache&apos; element..
        /// </summary>
        internal static string EM125 {
            get {
                return ResourceManager.GetString("EM125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;cache-id&apos; not specified in configuration..
        /// </summary>
        internal static string EM126 {
            get {
                return ResourceManager.GetString("EM126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not locate cache configuration file. Installation might be corrupt.
        /// </summary>
        internal static string EM127 {
            get {
                return ResourceManager.GetString("EM127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permissions to perform this operation.
        /// </summary>
        internal static string EM128 {
            get {
                return ResourceManager.GetString("EM128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not locate cache configuration file. Installation might be corrupt..
        /// </summary>
        internal static string EM129 {
            get {
                return ResourceManager.GetString("EM129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache ID can not be null.
        /// </summary>
        internal static string EM130 {
            get {
                return ResourceManager.GetString("EM130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified cacheId is not registered.
        /// </summary>
        internal static string EM131 {
            get {
                return ResourceManager.GetString("EM131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null value for settings..
        /// </summary>
        internal static string EM132 {
            get {
                return ResourceManager.GetString("EM132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already registered..
        /// </summary>
        internal static string EM133 {
            get {
                return ResourceManager.GetString("EM133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to stop the cache.
        /// </summary>
        internal static string EM134 {
            get {
                return ResourceManager.GetString("EM134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to apply configuration.
        /// </summary>
        internal static string EM135 {
            get {
                return ResourceManager.GetString("EM135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly name can not be null.
        /// </summary>
        internal static string EM136 {
            get {
                return ResourceManager.GetString("EM136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type can not be null.
        /// </summary>
        internal static string EM137 {
            get {
                return ResourceManager.GetString("EM137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings not found in cluster map.
        /// </summary>
        internal static string EM138 {
            get {
                return ResourceManager.GetString("EM138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings not found in local cache map.
        /// </summary>
        internal static string EM139 {
            get {
                return ResourceManager.GetString("EM139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache &apos;.
        /// </summary>
        internal static string EM140 {
            get {
                return ResourceManager.GetString("EM140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project file seems to be of an older version. Please create a new project..
        /// </summary>
        internal static string EM141 {
            get {
                return ResourceManager.GetString("EM141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid project file.
        /// </summary>
        internal static string EM142 {
            get {
                return ResourceManager.GetString("EM142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update configuration..
        /// </summary>
        internal static string EM143 {
            get {
                return ResourceManager.GetString("EM143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not running..
        /// </summary>
        internal static string EM144 {
            get {
                return ResourceManager.GetString("EM144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not available.
        /// </summary>
        internal static string EM145 {
            get {
                return ResourceManager.GetString("EM145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cache exists with the same name.
        /// </summary>
        internal static string EM146 {
            get {
                return ResourceManager.GetString("EM146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error occured on the remote server.
        /// </summary>
        internal static string EM147 {
            get {
                return ResourceManager.GetString("EM147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already exists in.
        /// </summary>
        internal static string EM148 {
            get {
                return ResourceManager.GetString("EM148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid multicast address.
        /// </summary>
        internal static string EM149 {
            get {
                return ResourceManager.GetString("EM149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid server port.
        /// </summary>
        internal static string EM150 {
            get {
                return ResourceManager.GetString("EM150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NCache Queries only support premitive types. \.
        /// </summary>
        internal static string EM151 {
            get {
                return ResourceManager.GetString("EM151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node already have cluster &apos;.
        /// </summary>
        internal static string EM152 {
            get {
                return ResourceManager.GetString("EM152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to context cannot be null..
        /// </summary>
        internal static string EM153 {
            get {
                return ResourceManager.GetString("EM153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to session state is not available in this context..
        /// </summary>
        internal static string EM154 {
            get {
                return ResourceManager.GetString("EM154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is not HPTime.
        /// </summary>
        internal static string EM155 {
            get {
                return ResourceManager.GetString("EM155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to allocate plaintext buffer..
        /// </summary>
        internal static string EM156 {
            get {
                return ResourceManager.GetString("EM156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception marshalling data..
        /// </summary>
        internal static string EM157 {
            get {
                return ResourceManager.GetString("EM157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to allocate entropy data buffer..
        /// </summary>
        internal static string EM158 {
            get {
                return ResourceManager.GetString("EM158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception entropy marshalling data..
        /// </summary>
        internal static string EM159 {
            get {
                return ResourceManager.GetString("EM159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption failed..
        /// </summary>
        internal static string EM160 {
            get {
                return ResourceManager.GetString("EM160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception encrypting..
        /// </summary>
        internal static string EM161 {
            get {
                return ResourceManager.GetString("EM161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to allocate cipherText buffer..
        /// </summary>
        internal static string EM162 {
            get {
                return ResourceManager.GetString("EM162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to allocate entropy buffer..
        /// </summary>
        internal static string EM163 {
            get {
                return ResourceManager.GetString("EM163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decryption failed..
        /// </summary>
        internal static string EM164 {
            get {
                return ResourceManager.GetString("EM164", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception decrypting..
        /// </summary>
        internal static string EM165 {
            get {
                return ResourceManager.GetString("EM165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to format message for error code.
        /// </summary>
        internal static string EM166 {
            get {
                return ResourceManager.GetString("EM166", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing log path.
        /// </summary>
        internal static string EM167 {
            get {
                return ResourceManager.GetString("EM167", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to storageProvider.
        /// </summary>
        internal static string EM168 {
            get {
                return ResourceManager.GetString("EM168", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing cache store class..
        /// </summary>
        internal static string EM169 {
            get {
                return ResourceManager.GetString("EM169", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _mvPtr.
        /// </summary>
        internal static string EM170 {
            get {
                return ResourceManager.GetString("EM170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hFile.
        /// </summary>
        internal static string EM171 {
            get {
                return ResourceManager.GetString("EM171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to protection.
        /// </summary>
        internal static string EM172 {
            get {
                return ResourceManager.GetString("EM172", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offSet.
        /// </summary>
        internal static string EM173 {
            get {
                return ResourceManager.GetString("EM173", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to count.
        /// </summary>
        internal static string EM174 {
            get {
                return ResourceManager.GetString("EM174", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limited Virtual Memory. Your system has no paging file, or the paging file is too small..
        /// </summary>
        internal static string EM175 {
            get {
                return ResourceManager.GetString("EM175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maxLength.
        /// </summary>
        internal static string EM176 {
            get {
                return ResourceManager.GetString("EM176", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info.
        /// </summary>
        internal static string EM177 {
            get {
                return ResourceManager.GetString("EM177", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item.
        /// </summary>
        internal static string EM178 {
            get {
                return ResourceManager.GetString("EM178", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item size is larger than view size.
        /// </summary>
        internal static string EM179 {
            get {
                return ResourceManager.GetString("EM179", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string EM180 {
            get {
                return ResourceManager.GetString("EM180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No appropriate surrogate found for type.
        /// </summary>
        internal static string EM181 {
            get {
                return ResourceManager.GetString("EM181", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cacheContext can not be null.
        /// </summary>
        internal static string EM182 {
            get {
                return ResourceManager.GetString("EM182", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;.
        /// </summary>
        internal static string EM183 {
            get {
                return ResourceManager.GetString("EM183", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type handle.
        /// </summary>
        internal static string EM184 {
            get {
                return ResourceManager.GetString("EM184", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to surrogate.
        /// </summary>
        internal static string EM185 {
            get {
                return ResourceManager.GetString("EM185", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified type handle is already registered..
        /// </summary>
        internal static string EM186 {
            get {
                return ResourceManager.GetString("EM186", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to config.
        /// </summary>
        internal static string EM187 {
            get {
                return ResourceManager.GetString("EM187", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cacheName.
        /// </summary>
        internal static string EM188 {
            get {
                return ResourceManager.GetString("EM188", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RetrieveToken returned null.
        /// </summary>
        internal static string EM189 {
            get {
                return ResourceManager.GetString("EM189", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table sizes not initialized.
        /// </summary>
        internal static string EM190 {
            get {
                return ResourceManager.GetString("EM190", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table counts not initialized.
        /// </summary>
        internal static string EM191 {
            get {
                return ResourceManager.GetString("EM191", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong id for record.
        /// </summary>
        internal static string EM192 {
            get {
                return ResourceManager.GetString("EM192", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action for LALR state is null.
        /// </summary>
        internal static string EM193 {
            get {
                return ResourceManager.GetString("EM193", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error constructing GrammarReader.
        /// </summary>
        internal static string EM194 {
            get {
                return ResourceManager.GetString("EM194", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect file header.
        /// </summary>
        internal static string EM195 {
            get {
                return ResourceManager.GetString("EM195", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        internal static string EM196 {
            get {
                return ResourceManager.GetString("EM196", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided IIdentity object is null..
        /// </summary>
        internal static string EM197 {
            get {
                return ResourceManager.GetString("EM197", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided IIdentity object is incomplete or invalid..
        /// </summary>
        internal static string EM198 {
            get {
                return ResourceManager.GetString("EM198", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to principal.
        /// </summary>
        internal static string EM199 {
            get {
                return ResourceManager.GetString("EM199", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ruleName.
        /// </summary>
        internal static string EM200 {
            get {
                return ResourceManager.GetString("EM200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string EM201 {
            get {
                return ResourceManager.GetString("EM201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing security config file.
        /// </summary>
        internal static string EM202 {
            get {
                return ResourceManager.GetString("EM202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache is not registered.
        /// </summary>
        internal static string EM203 {
            get {
                return ResourceManager.GetString("EM203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache is not running.
        /// </summary>
        internal static string EM204 {
            get {
                return ResourceManager.GetString("EM204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server can not accept remote clients in this edition of NCache.
        /// </summary>
        internal static string EM205 {
            get {
                return ResourceManager.GetString("EM205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation could not be completed due to a timeout..
        /// </summary>
        public static string OperationFailed
        {
            get {
                return ResourceManager.GetString("EM206", resourceCulture);
            }
        }
    }
}
