@ECHO OFF

ECHO REMOVING ENVIRONMENT VARIABLE(S)...
ECHO ===================================
REG DELETE "HKLM\SYSTEM\CURRENTCONTROLSET\CONTROL\SESSION MANAGER\ENVIRONMENT" /V NCHOME /F
ECHO.

ECHO REMOVING REGISTRY VALUE(S) ...
ECHO ==============================
REG DELETE "HKLM\SOFTWARE\ALACHISOFT\NCACHE" /F
ECHO.
