using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Common;
using System.Runtime.Serialization;
using System.Text;

namespace System.Data.OleDb
{
    //
    // Summary:
    //     The exception that is thrown when the underlying provider returns a warning or
    //     error for an OLE DB data source. This class cannot be inherited.
    public sealed class OleDbException : DbException
    {
        //
        // Summary:
        //     Gets the HRESULT of the error.
        //
        // Returns:
        //     The HRESULT of the error.
        //[TypeConverter(typeof(ErrorCodeConverter))]
        public override int ErrorCode { get; }
        //
        // Summary:
        //     Gets a collection of one or more System.Data.OleDb.OleDbError objects that give
        //     detailed information about exceptions generated by the .NET Framework Data Provider
        //     for OLE DB.
        //
        // Returns:
        //     The collected instances of the System.Data.OleDb.OleDbError class.
        //[DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
        //public OleDbErrorCollection Errors { get; }

        //
        // Summary:
        //     This member overrides System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext).
        //
        // Parameters:
        //   si:
        //     The System.Runtime.Serialization.SerializationInfo that holds the serialized
        //     object data about the exception being thrown.
        //
        //   context:
        //     The System.Runtime.Serialization.StreamingContext that contains contextual information
        //     about the source or destination.
        //
        // Exceptions:
        //   T:System.ArgumentNullException:
        //     The si parameter is a null reference (Nothing in Visual Basic).
        public override void GetObjectData(SerializationInfo si, StreamingContext context)
        {
            //TODO: ALACHISOFT
            throw new NotImplementedException();
        }
    }
}
