// ==++==
//Copyright(c) Microsoft Corporation

//Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
//associated documentation files (the "Software"), to deal in the Software without restriction, 
//including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
//and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, 
//subject to the following conditions:

//The above copyright notice and this permission notice shall be included in all copies or substantial
//portions of the Software.

//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
//NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
//IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
//WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
//SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
// ==--==

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Common;
using System.Runtime.Serialization;
using System.Text;

namespace System.Data.OleDb
{
    //
    // Summary:
    //     The exception that is thrown when the underlying provider returns a warning or
    //     error for an OLE DB data source. This class cannot be inherited.
    public sealed class OleDbException : DbException
    {
        //
        // Summary:
        //     Gets the HRESULT of the error.
        //
        // Returns:
        //     The HRESULT of the error.
        //[TypeConverter(typeof(ErrorCodeConverter))]
        public override int ErrorCode { get; }
        //
        // Summary:
        //     Gets a collection of one or more System.Data.OleDb.OleDbError objects that give
        //     detailed information about exceptions generated by the .NET Framework Data Provider
        //     for OLE DB.
        //
        // Returns:
        //     The collected instances of the System.Data.OleDb.OleDbError class.
        //[DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
        //public OleDbErrorCollection Errors { get; }

        //
        // Summary:
        //     This member overrides System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext).
        //
        // Parameters:
        //   si:
        //     The System.Runtime.Serialization.SerializationInfo that holds the serialized
        //     object data about the exception being thrown.
        //
        //   context:
        //     The System.Runtime.Serialization.StreamingContext that contains contextual information
        //     about the source or destination.
        //
        // Exceptions:
        //   T:System.ArgumentNullException:
        //     The si parameter is a null reference (Nothing in Visual Basic).
        public override void GetObjectData(SerializationInfo si, StreamingContext context)
        {
            //TODO: ALACHISOFT
            throw new NotImplementedException();
        }
    }
}
